# https://gohugo.io/hosting-and-deployment/hosting-on-github/
# https://github.com/marketplace/actions/hugo-setup

name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v2

      - name: Scale Images
        run: |
          for dir in content/library/*/
          do
            for i in "$dir"/*.png
            do 
              convert "$i" -sample 200% "$(dirname $i)/1080_$(basename $i)"
              echo "Created $(dirname $i)/1080_$(basename $i)"
            done
          done
          for i in content/library/_index/*.png
          do 
            convert "$i" -sample 200% "$(dirname $i)/2x_$(basename $i)"
            echo "Created $(dirname $i)/2x_$(basename $i)"
          done

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Compress Videos
        run: |
          for dir in content/lectures/*/
          if ! [ -n "(echo $dir/*.mp4)"]; then continue; fi
          do
            for i in "$dir"/*.mp4
            do 
              ffmpeg -i "$i" -vcodec h264 -b:v 2000k -an "${i%.*}"_compressed.mp4
              echo "Created ${i%.*}_compressed.mp4"
            done
          done

      - name: Setup Hugo
        # uses: peaceiris/actions-hugo@v2.6.0
        # with:
        #   hugo-version: 'latest'
        #   # extended: true
        run: |
          pushd /tmp
          sudo apt-get install ca-certificates
          wget https://github.com/gohugoio/hugo/releases/download/v0.115.3/hugo_extended_0.115.3_Linux-64bit.tar.gz
          tar xzvf hugo_extended_0.115.3_Linux-64bit.tar.gz
          cp hugo /usr/local/bin
          popd
          hugo version

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public